### ISSUE TITLE
Smach Builder Implementation

### ISSUE THREAD

**Issue by dhled** [ScalABLE40/scxml_interpreter#2]
- [x] Create a simple state machine from skeleton
- [ ] Manager for API and integration
- [x] Userdata integration 
- [ ] Tests Implementation

Further features
- [x] Complex State Machine
- [x] QtSmachViewer Implementation
- [x] Better Introspection
- [ ] Complex State machine (SSM / ROS Smach integration)
- [ ] Tests Implementation

**Comment by dhled** [comment]
@rarrais  @tiagopinto7  @shrutisub 
SMACH Viewer implementation:
[https://github.com/ipa-led/qt_smach_viewer](https://github.com/ipa-led/qt_smach_viewer)

This version should be transparent, just use qt_smach_viewer.introspection.IntrospectionServer instead of smach_ros.
The executable:
`rosrun qt_smach_viewer smach_viewer`

This version should run better with heavy loaded state machine. The code is still a bit messy, I will clean it and open a pull request on the executive_smach and smach_viewer afterward.

**Comment by rarrais** [comment]
@ipa-led that's fantastic, as we had lots of issues using the standard one. 

We will have a look at it and give feedback
