### ISSUE TITLE
Correct builder for transition level callback

### ISSUE THREAD

**Issue by shrutisub** [ScalABLE40/scxml_interpreter#7]
current transition level callback not working (not implemented)

**Comment by dhled** [comment]
corrected in https://github.com/ScalABLE40/scxml_interpreter/pull/8

**Comment by dhled** [comment]
@shrutisub Please check that your SCXML is working with both way (Also check the overwrite of data, maybe we can add a parameter in the interface to see if we overwrite the data or not).
